### PR TITLE
implemented interface for search location page and query helpers

### PR DESCRIPTION
**Pull request by science-girl**
fixed merge conflict

more styling and added logo

added helper function

changed styling until fonts are linked

### CODE REVIEW

**Comment by science-girl** [comment]
When routing has been completed, we can finish this screen. The 'search' button will route to the results page with the query executed in the SearchLocationResult container.

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please remove your API keys from Github.

Please add a multiline comment to show what is your primary color and what is your accent color for this project instead of putting comments between codes. (styles.js)

Please remove Text import from js/index.js since you are not using it.

Please use LocationSearch.js file to export JSX using stateless component instead of doing it from the LoactionSearchContainer.js file. Add PropTypes to this file as well. 

Thank you!

**Comment by science-girl** [comment]
I have incorporated the suggested changes :-)

Thanks!

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please remove your API keys from here.

Please add propTypes to LocationSearchContainer.js.

Thank you!

**Comment by science-girl** [comment]
I removed the API Keys in the other branch - hideAPIKeys

**Comment by science-girl** [comment]
What sort of PropTypes should I be adding to LocationSearchContainer? I'm not sure I understand what I need to do. 

The way I understood it working was that when the user is routed to SearchLocation, there would not be any information passed at that point.  The user would search by location which is passed from the LocationSearchContainer to LocationSearch, the text of which is then routed to the screen listing results.

Thanks!

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
You are passing props to LocationSearch.js from LocationSearchContainer.js using props. If you are passing props, you should have propTypes to validate them. And I am sure you will take care of the API keys.

Thank you!

**Comment by science-girl** [comment]
The PropTypes are in LocationSearch, not in the container since this is where they are passed.  Should they be in the container too?

**Comment by science-girl** [comment]
removed proptypes :-)

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
I can still see your API keys in js/config/firebaseCongif.js file. Please remove them.

**Comment by science-girl** [comment]
That's because it's on a different branch that was approved before this one.  Once this branch is approved it will be merged in.

**Review by siddharthparmar7 — APPROVED** [review]
Thank you.

**Pull request merged**
