### PR TITLE
Created login page connected to Firebase

### PR DESCRIPTION
**Pull request by colinmj**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Your branch has conflict, please resolve it.

Are you planning to use Redux? do you guys wanna think about using Redux store to keep track of user sign in / sign out?

Thank you!

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Nice!! 

Suggestion: if you want to define your primary color and accent color, do it in the top of your file inside a multiline comment. (styles.js)

Remove Text and View imports from your js/index.js file since you are not using it.

Use Login.js file to export the JSX using stateless component instead of doing it from the LoginContainer.js file. 

Please, add propTypes to your LoginContainer.js. 
Think about using Redux store for Login and Logout methods. Otherwise, it looks good.

Thank you!

**Comment by colinmj** [comment]
Fixed merge conflicts

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Hey Colin,

I can still see this message, "This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts."

Maybe just create a new pull request.

Thank you.

**Pull request closed without merging**
