### PR TITLE
added initial directory structure and empty folders

### PR DESCRIPTION
**Pull request by science-girl**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
I can see this message with your pull request "added initial directory structure and empty folders has no dependencies". Please add an appropriate dependency. 

You should have styles.js and container.js (ex. login.js, loginContainer.js, styles.js) files for all of your screens.

Thank you!

**Comment by science-girl** [comment]
I tried to add a dependency but it is blocked

**Comment by science-girl** [comment]
made requested changes.

**Review by siddharthparmar7 — APPROVED** [review]
Thank you for making changes.

**Pull request merged**
